### ISSUE TITLE
Language server sends non-standard keys

### ISSUE THREAD

**Issue by galeo** [Microsoft/python-language-server#400]
It seems that this repo is being actively developed, but is there a special purpose to send non-standard keys `_version` and `_typenames` as a reply to a `textDocument/hover` request. I tried to use this language server in emacs with the [eglot](https://github.com/joaotavora/eglot) client and sadly it failed.

I opened an [issue](https://github.com/joaotavora/eglot/issues/144) in the eglot repo. From the reply of the eglot author, I think it is better to ask here why this language server does not follow the language server standard.

**Comment by jakebailey** [comment]
This language server is also integrated with PTVS, Python Tools for Visual Studio, which requires these values in many places. It might not be possible to remove them without breaking things, or some other consumer which depends on our existing public API surface.

I can, however, create a branch on my fork which ignores these keys over JSON-RPC, if you're willing to test it.

I'm a bit surprised that eglot is so strict in its decoding, though. VS Code, Sublime, and neovim (the clients with users I'm aware of) will happily ignore extra keys when decoding JSON into some known type. I haven't seen any JSON library which chooses to treat unexpected keys as errors by default. I'd be concerned about the language server protocol spec being expanded, a server like ours using those features, then eglot suddenly failing because there are new keys that were previously not there.

**Comment by AlexanderSher** [comment]
We can try to filter out `_` keys using [ContractResolver](https://www.newtonsoft.com/json/help/html/ContractResolver.htm): https://blog.rsuter.com/advanced-newtonsoft-json-dynamically-rename-or-ignore-properties-without-changing-the-serialized-class/

**Comment by jakebailey** [comment]
That'd work too, though requires that we always prefix out-of-spec things with an underscore. We already have one class which adds the `[NonSerialized]` attribute, but just in one place (and looking back at the PTVS repo for the git history doesn't explain why there and not elsewhere).

@galeo 	I have pushed a change to a branch in my fork, which will ignore any outgoing properties that start with `_`. I've only tested this by looking at the RPC trace in VS Code, so your mileage may vary.

https://github.com/jakebailey/python-language-server/tree/ignore-non-lsp-keys

**Comment by MikhailArkhipov** [comment]
Adherence to the LSP means sending data required by the LSP but does not mean limiting fields to the current LSP spec. Moreover, LSP itself is not fixed and new fields were added over the last few months to the existing structures such as CompletionItem. Addition of new fields did not break existing clients when servers started sending new structures. Per JSON communication client takes those fields it supports and ignores the rest. This way older clients work with newer servers just fine. 

So sending custom fields does not break the protocol as clients are not required to handle them. VS Code works with additional fields as does vim client as fast as we know.

Now, why these fields are there. They are for Visual Studio which provides much richer functionality and basic LSP is not sufficient for the VS editor. 

Also, servers can and do send custom RPC requests that should be ignored by the clients that do not support them. For example, this server may send telemetry or progress reports that currently are only handled by the Python extension to VS Code.

**Comment by galeo** [comment]
Hi, @jakebailey 

I've just tested your `ignore-non-lsp-keys` branch, it is workable now. However, the completion speed is not ideal and there are still some other problems that maybe caused by the eglot client. 

I've also responded to the eglot author and is waiting for a reply that if eglot would change its behavior and ignore the fields that it doesn't supported.

Thanks.

**Comment by MikhailArkhipov** [comment]
Closing since the behavior is by design.

**Comment by joaotavora** [comment]
@MikhailArkhipov, I'm the Eglot dev: here's my two cents.

> Adherence to the LSP means sending data required by the LSP but does not mean limiting fields to the current LSP spec

It does not say otherwise also.  You believe this interpretation to be correct, but I believe the other.  Note that if yours were correct  there would be no need for things like "$ Notifications and Requests".  And protocol versions would be mostly useless (and that the way they are done they really are a bit useless, but that's a different story)

I of course expected unsurmoutable resistance from a protocol bred from JS, where safety has always far lagged "pragmatism" (with questionable consequences).  So now, by default, Eglot will allow extraneous keys _by default_, so that the problem is fixed for all matters.  But it also has a strict mode of operation where it checks keys.

I don't expect to convince you of the benefits, but among them is that catching a mistyped field early is much easier that way.  This may not be important as the protocol is young, but as interfaces grown very long and objects get tossed around and modified it helps a lot when tracking bugs.  It's a different philosophy, perhaps: `&allow-other-keys` has existed for ~30 years in  Common Lisp, but, importantly, it's off by default. 

Also, when popular clients and populars servers start playing mostly to each other, things eventually get thrown into the spec which are popular, but not necessarily the best design.  

Eglot tried to offer some resistance to this, but eventually admits defeat :-)

**Comment by MikhailArkhipov** [comment]
Sending keys not in the current version or LSP is how LSP maintains backward compatibility. Ex fields were added to `CompletionItem` so updated servers started sending them but older clients worked fine. This is no different from sending custom fields. Otherwise every change to LSP would break all clients not supporting new version. This approach is no different from other areas that use protocols, like WiFi or cable modems. Older devices simple resort to handling older fields, new router does not prevent them from connecting even if it implements newer protocols.

**Comment by joaotavora** [comment]
> Otherwise every change to LSP would break all clients not supporting new version.

Not if client and server negotiate a protocol version, which LSP does purport to have, and which is what it should be there for.  If done properly, you can have backward-incompatible versions, which is a _good thing_.  If you don't you will soon have JS spaghetti instead of a proper language spec.  And it makes implementing clients a lot harder, eventually grinding things to a hlt.

Consider what happened to C++, just to name one example among many.

> This approach is no different from other areas that use protocols, like WiFi or cable modems. 

Sorry, but no.  There are of course examples that work like you say, but many others that aren't.
